services:
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: salles
    volumes:
      # - ./dbdata:/data/db
      - ./mongo-db/init-scripts/:/docker-entrypoint-initdb.d/